$(document).ready(function(){
    $(".logo").click(function(){
        $("#grid-area-1222").load("pages/page0.html");
    });
    $("#page1").click(function(){
        $("#grid-area-1222").load("pages/page1.html");
    });
    $("#page2").click(function(){
        $("#grid-area-1222").load("pages/page2.html");
    });
    $("#page3").click(function(){
        $("#grid-area-1222").load("pages/page3.html");
    });
    $("#page4").click(function(){
        $("#grid-area-1222").load("pages/page4.html");
    });
    $("#page5").click(function(){
        $("#grid-area-1222").load("pages/page5.html");
    });
    $("#page6").click(function(){
        $("#grid-area-1222").load("pages/page6.html");
    });
    $("#page7").click(function(){
        $("#grid-area-1222").load("pages/page7.html");
    });
});
